### ISSUE TITLE
Add a ChangeLog

### ISSUE THREAD

**Issue by postmodern** [jondot/padrino-warden#24]
I just upgraded from 0.1.0 to 0.20.1 and noticed the `authorize!` method is gone?! Please add a ChangeLog for users to read.

**Comment by postmodern** [comment]
Also, why the huge version bump from 0.1.0 to 0.20.0?

**Comment by Quintasan** [comment]
Certainly, the changelog issue makes perfect sense - I'll start writing them from nom on and maybe add some earlier entries.

As for the huge bump - it doesn't feel that huge to me.
I have been thinking of changing the versioning scheme to SemVer but I need to think about how to do it in a sensible manner.

**Comment by Quintasan** [comment]
I have started doing changelogs
https://github.com/jondot/padrino-warden/wiki/Changelog

**Comment by postmodern** [comment]
You might want to restrict who can edit the Wiki. Otherwise, I'm in ur ChangeLogs, stealing your edits.

**Comment by Quintasan** [comment]
@postmodern Thanks for the heads up but it appears that I do not have the rights to disable this so @jondot probably has to do it.
