### ISSUE TITLE
Make all app settings "safe" or else make it clear in the documentation that you should only set them after registration

### ISSUE THREAD

**Issue by jf** [jondot/padrino-warden#25]
The current situation right now is some settings are "special" (:auth_login_path, :auth_unauthenticated_path, :auth_logout_path, :default_strategies, :warden_failure_app), and can be safely set before `register Padrino::Warden`. Other settings **have** to be set **after** the register, or else during registration padrino-warden overwrites these settings, *even* if you've set them to some specific value.

I don't see a point to this arbitrary split, and making people either
(a) remember which settings are where ("safe", or "unsafe"; or "settable before register" vs "settable only after register")
(b) just set everything after the registration (in which case all of those protections (`unless app.respond_to?`) just seem pointless)
(c) read the source code to find out

I propose either make all of these settings "safe".... or else have them all *not* be safe, and then make a specific note about this in the documentation. Would appreciate your thoughts on this.

**Comment by Quintasan** [comment]
Sorry for the late response but I'm swamped with college-related stuff. I'll take a look at it this weekend.

**Comment by jf** [comment]
got it. Thanks for the update!

**Comment by Quintasan** [comment]
I had an internal debate about allowing users to disable sessions and I decided for it. It will render warden useless but I'm assuming you know what you are doing when disabling this.

I also created a wiki page which lists the possible options and default values for them
https://github.com/jondot/padrino-warden/wiki/Options

Do let me know if I messed something up.

**Comment by jf** [comment]
Thanks for going through all the settings and doing all that typing, @Quintasan ! Appreciate it. Ditto for the wiki page too.

I don't know if you'll want to do this change, but I was considering that you could iterate over a hash. The advantages are (a) it looks cleaner, (b) it's easier/quicker to see at a glance what all the settings and their defaults are, and (c) it's easier in the future as well (saves on typing!) to add future settings plus their defaults. If you're ok with this, I can do the typing this time and send you a PR :}

```
{
  # Enable sessions but allow the user to disable them explicitly
  sessions: true,

  auth_failure_path: '/',
  auth_success_path: '/',

  # set :auth_use_referrer to true to redirect a user back to an action
  # protected by 'login'/'authenticate' after successful login
  auth_use_referrer: false,

  auth_error_message: "You have provided invalid credentials.",
  auth_success_message: "You have logged in successfully.",

  ...
}.each do |setting, default|
    app.set setting, default unless app.respond_to? setting
end
```

**Comment by Quintasan** [comment]
Bleh, please do. I'll merge it for the next release.
